# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cloud_service.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'cloud_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x63loud_service.proto\x12\rcloud_service\"\x1c\n\x0b\x43lientInput\x12\r\n\x05input\x18\x01 \x01(\t\"\x1e\n\x0cServerOutput\x12\x0e\n\x06output\x18\x01 \x01(\t2a\n\x0c\x43loudService\x12Q\n\x12InteractiveSession\x12\x1a.cloud_service.ClientInput\x1a\x1b.cloud_service.ServerOutput(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cloud_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CLIENTINPUT']._serialized_start=38
  _globals['_CLIENTINPUT']._serialized_end=66
  _globals['_SERVEROUTPUT']._serialized_start=68
  _globals['_SERVEROUTPUT']._serialized_end=98
  _globals['_CLOUDSERVICE']._serialized_start=100
  _globals['_CLOUDSERVICE']._serialized_end=197
# @@protoc_insertion_point(module_scope)
