# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import cloud_service_pb2 as cloud__service__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in cloud_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CloudServiceStub(object):
    """Service gRPC pour l'interaction client-serveur
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InteractiveSession = channel.stream_stream(
                '/cloud_service.CloudService/InteractiveSession',
                request_serializer=cloud__service__pb2.ClientInput.SerializeToString,
                response_deserializer=cloud__service__pb2.ServerOutput.FromString,
                _registered_method=True)


class CloudServiceServicer(object):
    """Service gRPC pour l'interaction client-serveur
    """

    def InteractiveSession(self, request_iterator, context):
        """Méthode pour une session interactive bidirectionnelle
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CloudServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InteractiveSession': grpc.stream_stream_rpc_method_handler(
                    servicer.InteractiveSession,
                    request_deserializer=cloud__service__pb2.ClientInput.FromString,
                    response_serializer=cloud__service__pb2.ServerOutput.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cloud_service.CloudService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cloud_service.CloudService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CloudService(object):
    """Service gRPC pour l'interaction client-serveur
    """

    @staticmethod
    def InteractiveSession(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/cloud_service.CloudService/InteractiveSession',
            cloud__service__pb2.ClientInput.SerializeToString,
            cloud__service__pb2.ServerOutput.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
